workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      node: 18
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
