workflows:
  android-build:
    name: StopBetPro Android APK
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      vars:
        NODE_VERSION: 18
      node: 18
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          npx expo prebuild
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
