workflows:
  android_debug:
    name: Build Debug APK - StopBetPro
    max_build_duration: 60

    environment:
      node: 18.18.0
      java: 17
      vars:
        ANDROID_HOME: /opt/android-sdk-linux

    scripts:
      - name: Install Node dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Check project files
        script: |
          ls -R .

      - name: Build Debug APK
        script: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug --no-daemon

    artifacts:
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - mislene.souss789@gmail.com
