workflows:
  android-workflow:
    name: StopBet Pro Android
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 17
      node: 18
    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
